name: Upload

on:
  schedule:
    - cron: "25 6 * * *"
    - cron: "18 15 * * *"
    - cron: "18 2 * * *"
    - cron: "55 2 * * *"
    - cron: "17 0 * * *"
    - cron: "2 7 * * *"
  workflow_dispatch:

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  RYNX: ${{ secrets.RYNX }}
  CYBRIX: ${{ secrets.CYBRIX }}

jobs:
  scrape-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup FFmpeg
        uses: federicocarboni/setup-ffmpeg@v3.1

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12.2'

      - name: Install requirements
        run: pip install -r r.txt

      - name: Test env vars for python
        run: TEST_SECRET=${{ secrets.RYNX }}

      - name: Download
        run: python download.py

      - name: Process
        run: python post_main.py